XCX/urls.py
from rest_framework import routers

import userManagement.apiViews.appletApiViews as appletApiViews

from userManagement.appletViews import appletViews
from userManagement.manageViews import carViews
from userManagement.manageViews.goodViews import imageUpApi
from userManagement.userViews import userViews
from userManagement.manageViews import goodViews
from userManagement.manageViews import mainViews
from userManagement.manageViews import ordersViews
from userManagement.manageViews import questionViews
from userManagement.manageViews import showViews
from userManagement.rest import viewSet
import userManagement.util

from userManagement import manageViews, views
from django.conf.urls import include, url
from django.contrib import admin
import settings

"""XCX URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""


router = routers.DefaultRouter()
router.register(r'users', viewSet.UserViewSet)
router.register(r'goods', viewSet.GoodsViewSet)
router.register(r'show', viewSet.ShowViewSet)
router.register(r'question', viewSet.QuestionViewSet)
router.register(r'order', viewSet.OrderViewSet)
router.register(r'address', viewSet.AddressViewSet)
router.register(r'cars', viewSet.CarsViewSet)
router.register(r'carsapp', viewSet.CarsAppViewSet)
urlpatterns = [
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^api/', include(router.urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', userViews.login),
    url(r'^goods/', goodViews.goods),
    url(r'^index/', appletViews.index),
    url(r'^orders/', ordersViews.orders),
    url(r'^imageupapi/', imageUpApi),
    url(r'^getform/', goodViews.getGoodsForm),
    url(r'^getcarform/', carViews.getCarForm),
    url(r'^wxlogin/', userViews.wxLogin),
    url(r'^userinfo/', userViews.userInfo),
    url(r'^cartlist/', appletApiViews.cartList),
    url(r'^addcartlist/', appletApiViews.addCartList),
    url(r'^deletecart/', appletApiViews.deleteCart),
    url(r'^onlogin/', userViews.onLogin),
    url(r'^logout/', userViews.logout),
    url(r'^setting/', appletViews.setting),
    url(r'^resign/', userViews.resign),
    url(r'^createapplet/', appletViews.createApplet),
    url(r'^deleteapplet/', appletViews.deleteApplet),
    url(r'^weixincallback/', views.weixinCallBack),
    url(r'^getpaymentcode/', userManagement.util.getPaymentCode),
    url(r'^help/', views.help),
    url(r'^$', views.indexShow),
    url(r'^show/', appletApiViews.show),
    url(r'^question/', questionViews.question),
    url(r'^carsapp/', carViews.carsapp),
    url(r'^cars/', carViews.cars),
    url(r'^phone/', views.phoneCall),
    url(r'^phonecall/', views.phoneCall),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^article/(?P<category>\w+)/(?P<id>[1-9]\d*)/$', views.article),
    url(r'^article/(?P<category>\w+)/$', views.category),

]

userManagement/models.py
# coding:utf-8
from DjangoUeditor.models import UEditorField
from django.contrib.auth.models import User
from django.db import models
from django.db.models import signals
from django.dispatch import receiver


class GoodsType(models.Model):
    goodsType = models.CharField(u'分类', max_length=255)

    def __unicode__(self):
        return self.goodsType


class Brand(models.Model):
    brand = models.CharField(u'品牌', max_length=255)

    def __unicode__(self):
        return self.brand


class Goods(models.Model):
    goodsType = models.ForeignKey(GoodsType, null=True, blank=True)
    applet = models.ForeignKey('Applet')

    standard = models.CharField(u'规格', max_length=255, blank=True)

    goodsName = models.CharField(u'商品名', max_length=255)

    isAlive = models.BooleanField(u'是否上架销售', default=True)
    salesVolume = models.IntegerField(u"销量", default=0)
    price = models.FloatField(u'价格')
    thumbnail = models.ImageField(u'缩略图', upload_to='images', max_length=255, blank=True)
    productDetails = models.ImageField(u'商品详情', upload_to='images', max_length=255, blank=True)
    stock = models.IntegerField(u'库存', default=0)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)
    freeShipping = models.BooleanField(u'邮费', default=False)
    postage = models.FloatField(u'邮费', default=0.00)

    def __unicode__(self):
        return self.goodsName


class Cars(models.Model):
    brand = models.ForeignKey(GoodsType, null=True, blank=True)
    applet = models.ForeignKey('Applet')
    carName = models.CharField(u'商品名', max_length=255)
    price = models.FloatField(u'价格')
    image = models.ImageField(u'图', upload_to='images', max_length=255, blank=True)
    contact = models.TextField(u"介绍", blank=True)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)

    def __unicode__(self):
        return self.carName


class ManageUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=10, blank=True)
    name = models.CharField(u'昵称', max_length=255)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)
    accountPrice = models.FloatField(u'账户余额', default=0.0)
    cashApplicationChoices = ((0, u'已完成'), (1, u'申请提现'))
    cashApplication = models.IntegerField(u'提现申请状态', choices=cashApplicationChoices, default=0)
    zhifubaoCount = models.CharField(u'支付宝账号', blank=True, max_length=255)
    hasPermission = models.BooleanField(u"左右脑权限", default=False)

    def __unicode__(self):
        return self.user.username

    @receiver(signals.post_save, sender=User)
    def create_user_myuser(sender, instance, created, **kwargs):
        if created:
            ManageUser.objects.create(user=instance)

    @receiver(signals.post_save, sender=User)
    def save_user_myuser(sender, instance, **kwargs):
        if hasattr(instance, "user"):
            instance.user.save()


class Applet(models.Model):
    name = models.CharField(u'名称', max_length=255)
    description = models.CharField(u'描述', max_length=255, blank=True)
    image = models.ImageField(upload_to="images", blank=True, default="images/topLogo_LThzOqp.jpg")
    appletId = models.CharField(u"ID", max_length=255, blank=True)
    secret = models.CharField(u"secret", max_length=255, blank=True)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)
    appletType = ((2, "左右脑测试"), (0, "商城"), (1, "公司展示"), ((3, "车辆展示以及销售")))
    type = models.IntegerField(u'类型', choices=appletType, default=0)

    appletManageUser = models.ForeignKey(ManageUser)

    def __unicode__(self):
        return self.appletManageUser.user.username + " " + self.name


class AppletUser(models.Model):
    applet = models.ForeignKey(Applet)
    openid = models.CharField(max_length=255)
    session = models.CharField(max_length=255, blank=True)
    xcxSession = models.CharField(max_length=255, blank=True)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)
    phone = models.CharField(u"手机", max_length=255, blank=True)
    passWord = models.CharField(u"密码", max_length=255, blank=True)
    gender = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    province = models.CharField(max_length=255, blank=True)
    country = models.CharField(max_length=255, blank=True)
    avatarUrl = models.CharField(max_length=255, blank=True)
    nickname = models.CharField(max_length=255, blank=True)
    cart = models.CharField(u'购物车', max_length=255, default="[]")

    def __unicode__(self):
        return self.phone


class OrderGoods(models.Model):
    goods = models.ForeignKey(Goods)
    orderGoodsnumber = models.IntegerField(u'数量')
    orderForeignKey = models.ForeignKey('Order', null=True, blank=True)
    totalPrice = models.FloatField(u'总价', default=0.0)

    def __unicode__(self):
        return self.id.__str__()


class Order(models.Model):
    deliveryName = models.CharField(u'收获人名称', max_length=255, blank=True)
    deliveryPosition = models.CharField(u'送货位置', max_length=255, blank=True)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)
    orderStateChoices = ((-1, u'已删除'), (0, u'待付款'), (1, u'待发货'), (2, u'配送中'), (3, u'交易完成'))
    contact = models.CharField(u'电话', max_length=255, blank=True)
    orderState = models.IntegerField(u'订单状态', choices=orderStateChoices, default=0)
    originalPrice = models.FloatField(u'原价', default=0.0)
    totalPrice = models.FloatField(u'总价', default=0.0)
    payPrice = models.FloatField(u'支付总价', default=0.0)
    userForeignKey = models.ForeignKey(AppletUser, null=True)

    def __unicode__(self):
        return self.id.__str__()


class GoodsImage(models.Model):
    image = models.ImageField(upload_to='images', max_length=255)
    goodsImageForeignKey = models.ForeignKey(Goods, null=True, blank=True)

    def __unicode__(self):
        return self.image.name


class Address(models.Model):
    appletUserForeign = models.ForeignKey(AppletUser)
    name = models.CharField(u"姓名", max_length=255)
    detailAddress = models.CharField(u"地址", max_length=255, blank=True)
    contact = models.CharField(u'电话', max_length=255, blank=True)
    province = models.CharField(u'省', max_length=255, blank=True)
    city = models.CharField(u'市', max_length=255, blank=True)
    district = models.CharField(u'区', max_length=255, blank=True)
    countyName = models.CharField(u'国', max_length=255, blank=True)

    def __unicode__(self):
        return self.name


class ShowAppData(models.Model):
    applet = models.OneToOneField(Applet)
    indexImage = models.ImageField(u"首页图片", upload_to='images', max_length=255)
    contactMan = models.CharField(u"联系人", max_length=255)
    contactNumber = models.CharField(u"联系方式", max_length=255)
    contactLocation = models.CharField(u"地址", max_length=255)


class QuestionAppData(models.Model):
    applet = models.OneToOneField(Applet)
    image1 = models.ImageField(u"广告图片1", blank=True, upload_to='images', max_length=255)
    image2 = models.ImageField(u"广告图片2", blank=True, upload_to='images', max_length=255)
    image3 = models.ImageField(u"广告图片3", blank=True, upload_to='images', max_length=255)


class CarAppData(models.Model):
    applet = models.OneToOneField(Applet)
    title = models.CharField(u"标题", blank=True, max_length=255)
    phone = models.CharField(u"电话", blank=True, max_length=255)
    contact = models.CharField(u'内容简介', blank=True, max_length=255)
    location = models.CharField(u'位置', blank=True, max_length=255)
    logo = models.ImageField(u"logo", blank=True, upload_to='images', max_length=255)


class Phone(models.Model):
    phone = models.CharField(u"电话号码", max_length=18)
    name = models.CharField(u'姓名', max_length=255, blank=True)
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)


class ArticleCategory(models.Model):
    name = models.CharField(u'名称', max_length=100)
    url = models.CharField(u'链接地址', max_length=100)
    def __unicode__(self):
        return self.name


class Article(models.Model):
    modDateTime = models.DateTimeField(u'最后修改日期', auto_now=True)
    createDateTime = models.DateTimeField(u'创建日期', auto_now_add=True)
    categoryForeign=models.ForeignKey(ArticleCategory)
    author=models.CharField(u'作者',max_length=255,default=u'予丰科技')
    title = models.CharField(u'标题', max_length=255)
    content = UEditorField(u'内容', width=1000, height=400, toolbars="full",
                           upload_settings={"imageMaxSize": 1204000},
                           settings={}, command=None, blank=True)
    def __unicode__(self):
        return self.title

userManagement/views.py
# coding:utf-8
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from forms import *
from util import *

reload(sys)
sys.setdefaultencoding('utf8')


def weixinCallBack(request):
    if request.method == 'POST':
        xml = request.body
        mtrade_status = (read_xml(xml, "return_code"))

        if (mtrade_status == 'SUCCESS'):
            mOrder = Order.objects.get(id=(read_xml(xml, "attach")))
            mOrder.orderState = 1
            mOrder.save()

        return HttpResponse(
            "<xml><return_code><![CDATA[SUCCESS]]></return_code><return_msg><![CDATA[OK]]></return_msg></xml>")


def help(request):
    return render(request, 'userManagement/help.html')


def indexShow(request):
    articleCategorys = ArticleCategory.objects.all()[:4]
    # TODO 硬编码此处
    # articles = get_object_or_404(ArticleCategory, url="xcx").article_set.all()
    return render(request, 'userManagement/indexshow.html', {"articleCategorys": articleCategorys})


def phone(request):
    if request.method == "POST":
        Phone.objects.create(phone=request.POST.get("phone"))
        return HttpResponse("ok", status=201)


def phoneCall(request):
    if request.method == "GET":
        # Phone.objects.filter()
        list = []
        list.append({"name": "da", "phone": "18888"})
        return render(request, 'userManagement/callPhoneManagement.html', {"data": list})
    if request.method == "POST":
        id = request.POST.get("id")
        name = request.POST.get("name", "")
        occupation = request.POST.get("occupation", "")
        location = request.POST.get('location', "")
        remarks = request.POST.get("remarks", "")
        nextCall = request.POST.get("nextCall", "")
        phone = get_object_or_404(Phone, id=id)

        phone.name = name
        phone.occupation = occupation
        phone.location = location
        phone.remarks = remarks
        phone.save()
        return HttpResponseRedirect('/phone/')


def article(request, category, id):
    # TODO 此处可优化到html中
    if request.method == "GET":
        allCategory = ArticleCategory.objects.all()
        article = get_object_or_404(Article, id=id)
        articleCategoryList = ArticleCategory.objects.filter(url=category)
        categoryName = ""
        if articleCategoryList.count() == 1:
            categoryName = articleCategoryList[0].name

        try:
            next = article.get_next_by_modDateTime()
        except ObjectDoesNotExist:
            next = None
        try:
            previous = article.get_previous_by_modDateTime()
        except ObjectDoesNotExist:
            previous = None

        return render(request, 'userManagement/article.html',
                      {"article": article, "category": category, "categoryName": categoryName,
                       "allCategory": allCategory, "next": next, "previous": previous})


def category(request, category):
    if request.method == "GET":
        categoryobjs = get_object_or_404(ArticleCategory, url=category).article_set.all()
        paginator = Paginator(categoryobjs, 8)
        page = request.GET.get('page', 1)
        allCategory = ArticleCategory.objects.all()
        try:
            # a = request.user.groups.all()[0].id
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)
        return render(request, 'userManagement/article.html',
                      {"Len": paginator.num_pages, "categoryobjs": contacts, "category": category,
                       "allCategory": allCategory})

templates/userManagement/article.html
{% extends 'userManagement/indexFormat.html' %}
{% load staticfiles %}
{% block title %}
    {% if article %}
        <title>{{ article.title }}</title>
    {% elif categoryobjs %}
        <title>{{ category }}_予丰科技_小程序一键生成</title>
    {% else %}
        <title>予丰科技_小程序一键生成</title>
    {% endif %}
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'userManagement/article/css/article.css' %}"/>
    <link rel="stylesheet" href="{% static 'userManagement/public/css/page.css' %}"/>

    <script src="{% static 'userManagement/public/js/jquery.page.js' %}"></script>
    <script type="text/javascript" charset="utf-8"
            src="https://static.bshare.cn/b/buttonLite.js#style=-1&amp;uuid=&amp;pophcol=2&amp;lang=zh"></script>
    <script type="text/javascript" charset="utf-8" src="https://static.bshare.cn/b/bshareC0.js"></script>

{% endblock %}
{% block body %}
    <div class="content">
        <div class="c_left">
            <ol class="breadcrumb">
                <li><a href="/">主页</a></li>
                <li><a href="/article/{{ category }}/">{{ categoryName }}</a></li>
                {% if article %}
                    <li class="active">{{ article.title }}</li>
                {% endif %}
            </ol>

            {% if article %}
                <div class="main-content">
                    <h3 class="article-text">{{ article.title }}</h3>
                    <h5 class="article-text">{{ article.modDateTime|date:"Y年n月j日" }} 作者:{{ article.author }} 类目:<a
                            href="/article/{{ category }}/">{{ categoryName }}</a></h5>
                    <div class="article-content"> {{ article.content |safe }}</div>
                    <div class="next_previous"><span>上一篇:{% if next %}
                        <a href="/article/{{ next.categoryForeign.url }}/{{ next.id }}/">{{ next.title }}</a>
                    {% else %}
                        没有了
                    {% endif %}</span><span>下一篇:{% if previous %}
                        <a href="/article/{{ previous.categoryForeign.url }}/{{ previous.id }}/">{{ previous.title }}</a>
                    {% else %}
                        没有了
                    {% endif %}</span></div>
                    <div class="bshare-custom"><a title="分享到QQ空间" class="bshare-qzone"></a><a title="分享到新浪微博"
                                                                                              class="bshare-sinaminiblog"></a><a
                            title="分享到人人网" class="bshare-renren"></a><a title="分享到腾讯微博" class="bshare-qqmb"></a><a
                            title="分享到网易微博" class="bshare-neteasemb"></a><a title="更多平台"
                                                                            class="bshare-more bshare-more-icon more-style-addthis"></a><span
                            class="BSHARE_COUNT bshare-share-count">0</span></div>

                </div>
            {% elif categoryobjs %}
                <div class="main-content">{% for categoryobj in categoryobjs %}
                    <ul class="arclist">
                        <li><span>{{ forloop.counter }}</span><a href="/article/{{ category }}/{{ categoryobj.id }}"
                                                                 class="title"
                                                                 title="{{ categoryobj.title }}">{{ categoryobj.title }}</a>
                            <p>{{ categoryobj.content|striptags|truncatechars:76 }}</p>
                        </li>
                    </ul>
                {% endfor %}
                </div>

            {% endif %}

        </div>
        <div class="nright">

            <h3>资讯栏目</h3>
            <ul class="article-all">
                {% for foo in allCategory %}
                    <li><a href="/{{ foo.url }}/" title="{{ foo.name }}"> {{ foo.name }} </a></li>
                {% endfor %}


            </ul>
            <div class="line1"></div>
            <h3>标签聚合</h3>
            <ul class="taglist">
                <li>
                    <a href="https://xcx.yibangbang99.com/article/xcx/1/">小程序</a>
                </li>


            </ul>
        </div>
    </div>
    {% if Len %}


        <div class="fen" style="margin-top: -25px">
            <div id="page"></div>
        </div>
    {% endif %}
    <script>
        var len = {{ Len|safe }};

        function getUrlParam(name) {
            var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)"); //构造一个含有目标参数的正则表达式对象
            var r = window.location.search.substr(1).match(reg);  //匹配目标参数
            if (r != null) return unescape(r[2]);
            return 1; //返回参数值
        }

        function changeURLArg(url, arg, arg_val) {
            var pattern = arg + '=([^&]*)';
            var replaceText = arg + '=' + arg_val;
            if (url.match(pattern)) {
                if (arg_val == undefined) {
                    replaceText = ""

                }
                var tmp = '/(' + arg + '=)([^&]*)/gi';
                tmp = url.replace(eval(tmp), replaceText);
                return tmp;
            } else {
                if (arg_val == undefined) {
                    return url

                }
                if (url.match('[\?]')) {
                    return url + '&' + replaceText;
                } else {
                    return url + '?' + replaceText;
                }
            }
            return url + '\n' + arg + '\n' + arg_val;
        }

        function setPages() {
            $("#page").createPage({
                pageCount: len,
                current: getUrlParam("page"),
                backFn: function (p) {
                    console.log(p);
                    var url = changeURLArg(window.location.href, "page", p);
                    window.location.href = changeURLArg(window.location.href, "page", p)
                }
            });
        }

        $(function () {
            setPages()
        })

    </script>
{% endblock %}

templates/userManagement/callPhoneManagement.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<link href="{% static 'userManagement/public/css/mains.css' %}" rel="stylesheet"/>
<link href="{% static 'userManagement/phoneCall/css/phoneCall.css' %}" rel="stylesheet"/>
<body>
<div class="mains" id="mains">


    <table class="table table-hover goods-list-table">
        <thead>
        <tr>

            <th data-field="title" type-name="文本">电话</th>
            <th data-field="title" type-name="文本">姓名</th>

            <th data-field="cover" type-name="图片">职业</th>
            <th data-field="cover" type-name="图片">地区</th>

            <th data-field="cover" type-name="图片">几天后提醒</th>
            <th data-field="cover" type-name="图片">备注</th>
            <th data-field="cover" type-name="图片">完成</th>

        </tr>
        </thead>
        <tbody id="goodstbody">
        {% for foo in data %}

            <tr>
                <form method="post">
                    <input name="id" value="{{ foo.id }}" style="display: none"/>
                    <td><a href="tel://+86{{ foo.phone }}">{{ foo.phone }}</a></td>
                    <td><input name="name" value="{{ foo.name }}"/></td>
                    <td><input name="occupation" value="{{ foo.occupation }}"/></td>
                    <td><input name="location" value="{{ foo.location }}"/></td>
                    <td><input name="nextCall" value=""/></td>
                    <td><input name="remarks" value="{{ foo.remarks }}"/></td>
                    <td><input type="submit" value="Submit"/></td>
                </form>
            </tr>

        {% endfor %}


        </tbody>
    </table>
    <div class="fen">
        <div id="page"></div>


    </div>


</div>
</body>
</html>

templates/userManagement/carsAppletManagement.html
{% extends 'userManagement/managementFormat.html' %}
{% load staticfiles %}
{% block body %}<div class="mains"><form method='post' enctype="multipart/form-data">{{ form }}
    <input type="submit" value="保存"/>
    </form>
</div>{% endblock %}

</form>
{% block carsaappletsidebar %}active{% endblock %}
{% block carssidebar %}{% endblock %}

templates/userManagement/index.html
{% extends 'userManagement/indexFormat.html' %}
{% load staticfiles %}
{% block body %}

    <div class="mask_app_setting">
        <div class="content_app_setting">
            <div class="set-modal-title">
                <div class="title-text">基本设置</div>
                <div class="close-btn">x</div>
            </div>
            <div class="set-modal-content">
                <form id="applet-form">
                    <div class="set-detail-item">

                        <div class="set-app-info">

                            <input class="publish-title-input" type="text" name="name" placeholder="我的应用">
                            <label>*</label>
                            <textarea class="publish-desc-input" name="description" placeholder="应用描述"></textarea>
                            <div>


                                <label id="id_type">类型:</label>

                                <select id="id_type" name="type">
                                    {% for applet_type in applet_types %}
                                        <option value="{{ applet_type.0 }}">{{ applet_type.1 }}</option>
                                    {% endfor %}</select>


                            </div>
                        </div>
                    </div>
                    <div class="set-detail-item">

                        <input class="image-input" type="file" accept="image/*" name="image"/>

                        <div class="set-logo-info">
                            <p>Logo用于二维码及登录页面</p>
                            <p>建议图片尺寸 32*32</p>
                        </div>
                    </div>

                </form>

            </div>
            <div class="set-modal-btn">
                <div class="cancel-btn">取消</div>
                <div class="save-btn">保存</div>
            </div>
        </div>
    </div>



    <div class="container">
        <div class="top_manage_info">

        </div>

        <div class="my-app-wrap">
            <ul class="app-container no-more" id="app-container">
                <li class="add" is-vip="0"><img src="{% static 'userManagement/myXcx/img/add.jpg' %}" alt="">
                    <p>创建新小程序</p></li>
                {% for applet in applet_list %}



                    <li class="info" data-vend_status="0" data-vend_price="null" data-id="{{ applet.id }}"
                        data-logo="http://cdn.jisuapp.cn/zhichi_frontend/static/invitation/images/logo.png"
                        data-desc="我的应用">
                        <div class="info-top">
                            <div class="tool-show">
                                <a class="nav_item" href="/setting/?id={{ applet.id }}">导出</a>
                                <a class="nav_item"
                                   href="/{% if applet.type == 0 %}goods{% elif applet.type == 1 %}show{% elif applet.type == 2 %}question{% elif applet.type == 3 %}carsapp{% endif %}/?id={{ applet.id }}">管理</a>
                                <a class="delete-applet nav_item" data-id="{{ applet.id }}">删除</a>


                            </div>
                            <img class="info-pic" src="{% static 'userManagement/myXcx/img/xcxapp208.jpg' %}"></div>
                        <div class="info-bottom"><a
                                href=""
                                target="_blank"><p>{{ applet.name }}</p></a>
                            <p class="info-title"><label class="detail"><span
                                    class="add_time"></span>{{ applet.createDateTime|date:"o-m-j" }}</label><label

                                    class="viewCou"></p></div>
                    </li>
                {% endfor %}

            </ul>

        </div>

    </div>




{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'userManagement/myXcx/css/myapp.css' %}">
    <script type="text/javascript" src="{% static 'userManagement/myXcx/js/myapp.js' %}"></script>
{% endblock %}
{% block title %}
    <title>予丰科技-我的应用</title>
{% endblock %}
{% block appmanage %}active{% endblock %}

templates/userManagement/questionManagement.html
{% extends 'userManagement/managementFormat.html' %}
{% load staticfiles %}

{% block body %}<div class="mains"><form method='post' enctype="multipart/form-data">{{ form }}
    <input type="submit" value="保存"/>
    </form>
</div>{% endblock %}

</form>
{% block questionsidebar %}active{% endblock %}
{% block showsidebar %}none{% endblock %}
{% block ordersidebar %}none{% endblock %}
{% block goodssidebar %}none{% endblock %}
{% block paysidebar %}none{% endblock %}
{% block moneysidebar %}none{% endblock %}